apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-deployment
spec: 
  selector:
    matchLabels:
      app: posts
  replicas: 1
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: posts:v2